set(GRAMMAR_DIR "${CMAKE_SOURCE_DIR}/esp/services/ws_sql/sql2ecl/grammars")
set(OUTPUT_DIR "${CMAKE_SOURCE_DIR}/esp/services/ws_sql/sql2ecl")
set(GRAMMAR_PREFIX "MySQL")
set(ANTLR4_GRAMMAR_LEXER "${GRAMMAR_PREFIX}Lexer.g4")
set(ANTLR4_GRAMMAR_PARSER "${GRAMMAR_PREFIX}Parser.g4")

set(ANTLR4_GENERATED_SOURCE
	${OUTPUT_DIR}/${GRAMMAR_PREFIX}Lexer.cpp
	${OUTPUT_DIR}/${GRAMMAR_PREFIX}Parser.cpp
	${OUTPUT_DIR}/${GRAMMAR_PREFIX}ParserBaseListener.cpp
	${OUTPUT_DIR}/${GRAMMAR_PREFIX}ParserListener.cpp
)
set(ANTLR4_GENERATED_HEADER
	${OUTPUT_DIR}/${GRAMMAR_PREFIX}Lexer.h
	${OUTPUT_DIR}/${GRAMMAR_PREFIX}Parser.h
	${OUTPUT_DIR}/${GRAMMAR_PREFIX}ParserBaseListener.h
	${OUTPUT_DIR}/${GRAMMAR_PREFIX}ParserListener.h
)

set(ANTLR4_GENERATED_MISC
	${OUTPUT_DIR}/${GRAMMAR_PREFIX}Parser.tokens
	${OUTPUT_DIR}/${GRAMMAR_PREFIX}Lexer.tokens
)

find_package(Java REQUIRED)
find_package(ANTLR REQUIRED)
	
add_custom_command(OUTPUT ${ANTLR4_GENERATED_SOURCE} ${ANTLR4_GENERATED_HEADER} ${ANTLR4_GENERATED_MISC}
	COMMAND ${Java_JAVA_EXECUTABLE} "-jar" ${ANTLR_BUILDTIME_JAR} "-Dlanguage=Cpp" ${GRAMMAR_DIR}/${ANTLR4_GRAMMAR_LEXER} ${GRAMMAR_DIR}/${ANTLR4_GRAMMAR_PARSER} "-o" ${OUTPUT_DIR}
	COMMENT "Generating ANTLR4 Lexer, Parser, and Listeners from grammars"
)
add_custom_target(antlr-generated-listener
	DEPENDS ${ANTLR4_GENERATED_SOURCE} ${ANTLR4_GENERATED_HEADER} ${ANTLR4_GENERATED_MISC}
)

mark_as_advanced(ANTLR4_GENERATED_SOURCE ANTLR4_GENERATED_HEADER ANTLR4_GENERATED_MISC)
